In [34]:
import numpy as np
def matr(a, b):
    s=0
    n=len(a)
    x=np.zeros(3)
    for k in range(n-1, -1, -1):
        s=0
        for j in range(k+1, n, 1):
            s=s+a[k][j]*x[j]
        x[k]=(b[k]-s)/a[k][k]            
    return x
def mats(a, b):
    n=len(a)
    for k in range (0, n-1, 1):
        for i in range (k+1, n, 1):
            m=a[i][k]/a[k][k]
            a[i][k]=0
            for j in range (k+1, n, 1):
                a[i][j]=a[i][j]-(m*a[k][j])
                b[i]=b[i]-m*b[k]
    return a1, b1                
m1=np.array([[3, 2, 4], [0, 1/3, 2/3], [0, 0, -8]])
m2=np.array([1, 5/3, 0])
print(matr(m1,m2))
m3=np.array([[2, 1, -3], [-1, 3, 2], [3, 1, -3]])
m4=np.array([-1, 12, 0])
print('\n', m3)
a1, b1=mats(m3, m4)
print('\n', m3)
print(matr(m3,m4))

[-3.  5. -0.]

 [[ 2  1 -3]
 [-1  3  2]
 [ 3  1 -3]]

 [[ 2  1 -3]
 [ 0  3  0]
 [ 0  0  1]]
[0.83333333 3.33333333 2.        ]
